import type { Metadata } from 'next'
import VideoPageWrapper from './VideoPageWrapper'
import { createServiceClient } from '@/lib/supabase/service'

export async function generateMetadata({ searchParams }: { searchParams?: { prompt?: string } }): Promise<Metadata> {
  const prompt = searchParams?.prompt
  
  // 尝试从数据库获取SEO配置
  let seoConfig: { title: string; description: string | null } | null = null
  
  if (prompt) {
    try {
      const supabase = await createServiceClient()
      const pageUrl = `/video?prompt=${encodeURIComponent(prompt)}`
      
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data } = await (supabase as any)
        .from('dynamic_page_seo')
        .select('title, description')
        .eq('page_url', pageUrl)
        .eq('is_active', true)
        .order('priority', { ascending: false })
        .limit(1)
        .single()
      
      if (data && typeof data === 'object' && 'title' in data) {
        seoConfig = {
          title: data.title as string,
          description: data.description as string | null,
        }
      }
    } catch (error) {
      // 如果查询失败，使用默认逻辑
      console.error('获取SEO配置失败:', error)
    }
  } else {
    // 无 prompt 时，也尝试获取默认配置
    try {
      const supabase = await createServiceClient()
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data } = await (supabase as any)
        .from('dynamic_page_seo')
        .select('title, description')
        .eq('page_path', '/video')
        .eq('page_url', '/video')
        .eq('is_active', true)
        .order('priority', { ascending: false })
        .limit(1)
        .single()
      
      if (data && typeof data === 'object' && 'title' in data) {
        seoConfig = {
          title: data.title as string,
          description: data.description as string | null,
        }
      }
    } catch (error) {
      // 如果查询失败，使用默认逻辑
      console.error('获取SEO配置失败:', error)
    }
  }
  
  // 如果数据库中有配置，使用数据库配置
  if (seoConfig) {
    return {
      title: seoConfig.title,
      description: seoConfig.description || undefined,
    }
  }
  
  // 否则使用默认动态生成逻辑
  if (prompt) {
    // 截取 prompt 的前 80 个字符作为 description 的一部分，确保唯一性
    const promptPreview = prompt.length > 80 ? prompt.substring(0, 80) + '...' : prompt
    // 为每个 prompt 生成更独特的描述，包含更多 prompt 内容
    // 使用 prompt 的哈希或长度来增加唯一性
    const promptHash = prompt.length % 1000
    const uniqueDescription = `AI video: "${promptPreview}". Generated by Sora2Ai with OpenAI Sora 2.0. ${prompt.length > 100 ? 'Watch the full video creation process.' : 'Create similar videos instantly.'} Video ID: ${promptHash}`
    return {
      title: `Generate: ${promptPreview.substring(0, 50)}${prompt.length > 50 ? '...' : ''}`,
      description: uniqueDescription,
    }
  }

  return {
    title: 'Video Generator - Create AI Videos from Text',
    description: 'Transform text prompts into professional AI videos instantly. Sora2Ai video generator uses OpenAI Sora 2.0 to create high-quality content from your descriptions.',
  }
}

export default function VideoPage({ searchParams }: { searchParams?: { prompt?: string } }) {
  const prompt = searchParams?.prompt
  
  // Structured Data for Video Generation Page
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: prompt ? `Generate Video: ${prompt.substring(0, 50)}...` : 'Video Generator - Create AI Videos from Text',
    description: prompt 
      ? `Generate AI video with prompt: ${prompt.substring(0, 100)}...`
      : 'Transform text prompts into professional AI videos instantly. Sora2Ai video generator uses OpenAI Sora 2.0 to create high-quality content from your descriptions.',
    url: prompt 
      ? `https://sora2aivideos.com/video?prompt=${encodeURIComponent(prompt)}`
      : 'https://sora2aivideos.com/video',
    mainEntity: {
      '@type': 'SoftwareApplication',
      name: 'Sora2Ai Video Generator',
      applicationCategory: 'MultimediaApplication',
      operatingSystem: 'Web',
      featureList: [
        'AI-powered video generation',
        'OpenAI Sora 2.0 technology',
        'Text-to-video conversion',
        'Multiple aspect ratios',
        'High-quality output',
      ],
    },
  }

  return (
    <>
      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <VideoPageWrapper />
    </>
  )
}
