import type { Metadata } from 'next'
import VideoPageWrapper from './VideoPageWrapper'

export async function generateMetadata({ searchParams }: { searchParams?: { prompt?: string } }): Promise<Metadata> {
  const prompt = searchParams?.prompt
  
  if (prompt) {
    // 截取 prompt 的前 80 个字符作为 description 的一部分，确保唯一性
    const promptPreview = prompt.length > 80 ? prompt.substring(0, 80) + '...' : prompt
    // 为每个 prompt 生成更独特的描述，包含更多 prompt 内容
    // 使用 prompt 的哈希或长度来增加唯一性
    const promptHash = prompt.length % 1000
    const uniqueDescription = `AI video: "${promptPreview}". Generated by Sora2Ai with OpenAI Sora 2.0. ${prompt.length > 100 ? 'Watch the full video creation process.' : 'Create similar videos instantly.'} Video ID: ${promptHash}`
    return {
      title: `Generate: ${promptPreview.substring(0, 50)}${prompt.length > 50 ? '...' : ''}`,
      description: uniqueDescription,
    }
  }

  return {
    title: 'Video Generator - Create AI Videos from Text',
    description: 'Transform text prompts into professional AI videos instantly. Sora2Ai video generator uses OpenAI Sora 2.0 to create high-quality content from your descriptions.',
  }
}

export default function VideoPage({ searchParams }: { searchParams?: { prompt?: string } }) {
  const prompt = searchParams?.prompt
  
  // Structured Data for Video Generation Page
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: prompt ? `Generate Video: ${prompt.substring(0, 50)}...` : 'Video Generator - Create AI Videos from Text',
    description: prompt 
      ? `Generate AI video with prompt: ${prompt.substring(0, 100)}...`
      : 'Transform text prompts into professional AI videos instantly. Sora2Ai video generator uses OpenAI Sora 2.0 to create high-quality content from your descriptions.',
    url: prompt 
      ? `https://sora2aivideos.com/video?prompt=${encodeURIComponent(prompt)}`
      : 'https://sora2aivideos.com/video',
    mainEntity: {
      '@type': 'SoftwareApplication',
      name: 'Sora2Ai Video Generator',
      applicationCategory: 'MultimediaApplication',
      operatingSystem: 'Web',
      featureList: [
        'AI-powered video generation',
        'OpenAI Sora 2.0 technology',
        'Text-to-video conversion',
        'Multiple aspect ratios',
        'High-quality output',
      ],
    },
  }

  return (
    <>
      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <VideoPageWrapper />
    </>
  )
}
