import type { Metadata } from 'next'
import VideoPageWrapper from './VideoPageWrapper'
import { createServiceClient } from '@/lib/supabase/service'

export async function generateMetadata({ searchParams }: { searchParams?: { prompt?: string } }): Promise<Metadata> {
  const prompt = searchParams?.prompt
  
  // Try to get SEO config from database
  let seoConfig: { title: string; description: string | null } | null = null
  
  if (prompt) {
    try {
      const supabase = await createServiceClient()
      const pageUrl = `/video?prompt=${encodeURIComponent(prompt)}`
      
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data } = await (supabase as any)
        .from('dynamic_page_seo')
        .select('title, description')
        .eq('page_url', pageUrl)
        .eq('is_active', true)
        .order('priority', { ascending: false })
        .limit(1)
        .single()
      
      if (data && typeof data === 'object' && 'title' in data) {
        seoConfig = {
          title: data.title as string,
          description: data.description as string | null,
        }
      }
    } catch (error) {
      // If query fails, use default logic
      console.error('Failed to get SEO config:', error)
    }
  } else {
    // When no prompt, also try to get default config
    try {
      const supabase = await createServiceClient()
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { data } = await (supabase as any)
        .from('dynamic_page_seo')
        .select('title, description')
        .eq('page_path', '/video')
        .eq('page_url', '/video')
        .eq('is_active', true)
        .order('priority', { ascending: false })
        .limit(1)
        .single()
      
      if (data && typeof data === 'object' && 'title' in data) {
        seoConfig = {
          title: data.title as string,
          description: data.description as string | null,
        }
      }
    } catch (error) {
      // If query fails, use default logic
      console.error('Failed to get SEO config:', error)
    }
  }
  
  // If config exists in database, use database config
  if (seoConfig) {
    return {
      title: seoConfig.title,
      description: seoConfig.description || undefined,
    }
  }
  
  // Otherwise use default dynamic generation logic
  if (prompt) {
    // Take first 80 characters of prompt as part of description to ensure uniqueness
    const promptPreview = prompt.length > 80 ? prompt.substring(0, 80) + '...' : prompt
    // Generate more unique description for each prompt, include more prompt content
    // Use prompt hash or length to increase uniqueness
    const promptHash = prompt.length % 1000
    const uniqueDescription = `AI video: "${promptPreview}". Generated by Sora2Ai with OpenAI Sora 2.0. ${prompt.length > 100 ? 'Watch the full video creation process.' : 'Create similar videos instantly.'} Video ID: ${promptHash}`
    return {
      title: `Generate: ${promptPreview.substring(0, 50)}${prompt.length > 50 ? '...' : ''}`,
      description: uniqueDescription,
    }
  }

  return {
    title: 'Video Generator - Create AI Videos from Text',
    description: 'Transform text prompts into professional AI videos instantly. Sora2Ai video generator uses OpenAI Sora 2.0 to create high-quality content from your descriptions.',
  }
}

export default function VideoPage({ searchParams }: { searchParams?: { prompt?: string } }) {
  const prompt = searchParams?.prompt
  
  // Structured Data for Video Generation Page
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: prompt ? `Generate Video: ${prompt.substring(0, 50)}...` : 'Video Generator - Create AI Videos from Text',
    description: prompt 
      ? `Generate AI video with prompt: ${prompt.substring(0, 100)}...`
      : 'Transform text prompts into professional AI videos instantly. Sora2Ai video generator uses OpenAI Sora 2.0 to create high-quality content from your descriptions.',
    url: prompt 
      ? `https://sora2aivideos.com/video?prompt=${encodeURIComponent(prompt)}`
      : 'https://sora2aivideos.com/video',
    mainEntity: {
      '@type': 'SoftwareApplication',
      name: 'Sora2Ai Video Generator',
      applicationCategory: 'MultimediaApplication',
      operatingSystem: 'Web',
      featureList: [
        'AI-powered video generation',
        'OpenAI Sora 2.0 technology',
        'Text-to-video conversion',
        'Multiple aspect ratios',
        'High-quality output',
      ],
    },
  }

  return (
    <>
      {/* Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      <VideoPageWrapper />
    </>
  )
}
