/**
 * 保存场景词到数据库（复用现有逻辑）
 */
export async function saveSceneToDatabase(
  industry: string,
  scene: { id: number; use_case: string },
  useCaseType: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: any
) {
  const { generateSlugFromText } = await import('@/lib/utils/slug')
  const { checkContentQuality } = await import('@/lib/utils/content-quality')

  // 从场景词中提取关键词作为标题
  const title = scene.use_case.length > 100 
    ? scene.use_case.substring(0, 100) + '...'
    : scene.use_case
  
  // 生成 slug，确保不会太长
  const sceneText = scene.use_case.length > 80 
    ? scene.use_case.substring(0, 80) 
    : scene.use_case
  const slug = generateSlugFromText(`${industry}-${sceneText}`)
  
  // 生成 H1 和描述
  const h1 = `AI Video Generation for ${scene.use_case} in ${industry}`
  const description = `Learn how to use AI video generation for ${scene.use_case} in the ${industry} industry. Create professional videos with Sora2.`

  // 生成完整内容
  const content = `# ${h1}

## Introduction

${scene.use_case}

## Why AI Video is Perfect for This Scenario

AI video generation offers several key advantages for ${scene.use_case} in the ${industry} industry:

- **Fast Production**: Create professional videos in minutes instead of days or weeks
- **Cost-Effective**: No need for expensive video production teams, equipment, or locations
- **Consistent Quality**: AI ensures professional output every time, maintaining brand consistency
- **Scalable**: Generate multiple variations easily for A/B testing or different markets
- **Flexible**: Quickly adapt videos for different platforms (YouTube, TikTok, Instagram, etc.)

## How to Use Sora2 for ${scene.use_case}

### Step 1: Create Your Video Prompt

Describe your ${scene.use_case} video needs in detail. Be specific about:
- The scene or setting
- The mood or tone
- Key elements or actions
- Style preferences (realistic, cinematic, animated, etc.)

### Step 2: Choose Video Settings

Select your preferred aspect ratio:
- **16:9** for YouTube, websites, presentations
- **9:16** for TikTok, Instagram Stories, Shorts
- **1:1** for Instagram posts, Facebook

Choose video duration: **10 seconds** or **15 seconds** based on your needs.

### Step 3: Generate Your Video

Click generate and wait a few moments. Sora2's AI will create your professional video with high-quality visuals and smooth transitions.

### Step 4: Download and Use

Once generated, download your video and use it immediately in your ${industry} marketing, training, or content strategy.

## Example Prompt for ${scene.use_case}

Here's an example prompt you can use with Sora2 to generate a **10-second or 15-second** video:

\`\`\`
[Example prompt based on the use case - will be generated based on scene description]
\`\`\`

**Note**: All videos generated by Sora2 are available in 10-second or 15-second durations. Choose the duration that best fits your content needs.

## Get Started Today

Start creating professional ${scene.use_case} videos for ${industry} today with Sora2 AI video generation platform. No technical skills required, no expensive equipment needed - just describe what you want, and AI will create it for you.`

  // 自动质量检查
  const qualityCheck = checkContentQuality({
    title,
    h1,
    description,
    content,
    seo_keywords: [scene.use_case, industry, `${industry} AI video`],
  })

  // 根据质量检查结果设置状态
  const qualityStatus = qualityCheck.passed && qualityCheck.score >= 70 ? 'approved' : 'pending'
  const isPublished = qualityStatus === 'approved'

  // 直接使用 Supabase 保存（避免 HTTP 调用）
  // 🔥 添加超时控制，避免数据库操作卡住
  const DB_TIMEOUT = 10000 // 10秒超时
  
  try {
    // 🔥 使用 Promise.race 确保超时控制
    const insertPromise = supabase
      .from('use_cases')
      .insert({
        slug,
        title,
        h1,
        description,
        content,
        use_case_type: useCaseType,
        industry,
        is_published: isPublished,
        seo_keywords: [scene.use_case, industry, `${industry} AI video`],
        quality_status: qualityStatus,
        quality_score: qualityCheck.score,
        quality_issues: qualityCheck.issues,
      })
      .select()
    
    const timeoutPromise = new Promise<{ error: { message?: string; code?: string; details?: string; hint?: string } | null }>((_, reject) =>
      setTimeout(() => reject(new Error('数据库保存超时（10秒）')), DB_TIMEOUT)
    )
    
    const { error: insertError } = await Promise.race([insertPromise, timeoutPromise]) as { error: { message?: string; code?: string; details?: string; hint?: string } | null }

    if (insertError) {
      // 如果是重复 slug，尝试添加后缀（也添加超时控制）
      if (insertError.code === '23505') {
        const newSlug = `${slug}-${Date.now()}`
        const retryInsertPromise = supabase
          .from('use_cases')
          .insert({
            slug: newSlug,
            title,
            h1,
            description,
            content,
            use_case_type: useCaseType,
            industry,
            is_published: isPublished,
            seo_keywords: [scene.use_case, industry, `${industry} AI video`],
            quality_status: qualityStatus,
            quality_score: qualityCheck.score,
            quality_issues: qualityCheck.issues,
          })
        
        const retryTimeoutPromise = new Promise<{ error: { message?: string; code?: string; details?: string; hint?: string } | null }>((_, reject) =>
          setTimeout(() => reject(new Error('数据库保存超时（10秒）')), DB_TIMEOUT)
        )
        
        const { error: retryError } = await Promise.race([retryInsertPromise, retryTimeoutPromise]) as { error: { message?: string; code?: string; details?: string; hint?: string } | null }
        
        if (retryError) {
          console.error(`[${industry}] 保存失败 (重复slug重试失败):`, {
            error: retryError.message,
            code: retryError.code,
            details: retryError.details,
            hint: retryError.hint,
            slug: newSlug,
          })
          throw new Error(`保存失败: ${retryError.message} (code: ${retryError.code})`)
        }
      } else {
        console.error(`[${industry}] 保存失败:`, {
          error: insertError.message,
          code: insertError.code,
          details: insertError.details,
          hint: insertError.hint,
          slug,
          useCaseType,
        })
        throw new Error(`保存失败: ${insertError.message} (code: ${insertError.code})`)
      }
    }
  } catch (error) {
    // 记录更详细的错误信息
    const errorMessage = error instanceof Error ? error.message : String(error)
    console.error(`[${industry}] 保存场景词异常:`, {
      error: errorMessage,
      sceneId: scene.id,
      sceneLength: scene.use_case.length,
      slug,
      useCaseType,
    })
    throw error
  }
}

