/**
 * 保存场景词到数据库（复用现有逻辑）
 */
export async function saveSceneToDatabase(
  industry: string,
  scene: { id: number; use_case: string },
  useCaseType: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: any
) {
  const { generateSlugFromText } = await import('@/lib/utils/slug')
  const { checkContentQuality } = await import('@/lib/utils/content-quality')
  const { createHash } = await import('crypto')

  // 从场景词中提取关键词作为标题
  const title = scene.use_case.length > 100 
    ? scene.use_case.substring(0, 100) + '...'
    : scene.use_case
  
  // 生成 slug，确保不会太长
  const sceneText = scene.use_case.length > 80 
    ? scene.use_case.substring(0, 80) 
    : scene.use_case
  // 🔥 防重复：对完整 use_case 做稳定 hash，避免重复跑任务时产生海量重复记录
  // 也避免过去“slug 冲突就加时间戳”导致的重复膨胀
  const useCaseHash = createHash('sha1')
    .update(scene.use_case.trim(), 'utf8')
    .digest('hex')
    .slice(0, 10)
  const slug = generateSlugFromText(`${industry}-${useCaseHash}-${sceneText}`)
  
  // 生成 H1 和描述
  const h1 = `AI Video Generation for ${scene.use_case} in ${industry}`
  const description = `Learn how to use AI video generation for ${scene.use_case} in the ${industry} industry. Create professional videos with Sora2.`

  // 🔥 先做轻量去重：同一 industry + use_case_type + h1 已存在，则跳过保存
  // 这能覆盖“历史旧 slug”导致的重复问题（不依赖 slug 冲突）
  try {
    const { data: existing } = await supabase
      .from('use_cases')
      .select('id')
      .eq('industry', industry)
      .eq('use_case_type', useCaseType)
      .eq('h1', h1)
      .limit(1)
      .maybeSingle()
    if (existing?.id) {
      const duplicateError = new Error('Duplicate use case (same industry + type + h1), skipped.') as Error & {
        isDuplicate?: boolean
      }
      duplicateError.isDuplicate = true
      throw duplicateError
    }
  } catch (dedupeCheckError) {
    // 如果是我们抛出的 duplicate，继续向上抛，让上层按“跳过”处理
    if ((dedupeCheckError as Error & { isDuplicate?: boolean })?.isDuplicate) {
      throw dedupeCheckError
    }
    // 去重查询失败不应阻断保存流程（例如临时连接问题）
    console.warn(`[${industry}] 去重检查失败（继续尝试保存）:`, dedupeCheckError)
  }

  // 生成完整内容
  const content = `# ${h1}

## Introduction

${scene.use_case}

## Why AI Video is Perfect for This Scenario

AI video generation offers several key advantages for ${scene.use_case} in the ${industry} industry:

- **Fast Production**: Create professional videos in minutes instead of days or weeks
- **Cost-Effective**: No need for expensive video production teams, equipment, or locations
- **Consistent Quality**: AI ensures professional output every time, maintaining brand consistency
- **Scalable**: Generate multiple variations easily for A/B testing or different markets
- **Flexible**: Quickly adapt videos for different platforms (YouTube, TikTok, Instagram, etc.)

## How to Use Sora2 for ${scene.use_case}

### Step 1: Create Your Video Prompt

Describe your ${scene.use_case} video needs in detail. Be specific about:
- The scene or setting
- The mood or tone
- Key elements or actions
- Style preferences (realistic, cinematic, animated, etc.)

### Step 2: Choose Video Settings

Select your preferred aspect ratio:
- **16:9** for YouTube, websites, presentations
- **9:16** for TikTok, Instagram Stories, Shorts
- **1:1** for Instagram posts, Facebook

Choose video duration: **10 seconds** or **15 seconds** based on your needs.

### Step 3: Generate Your Video

Click generate and wait a few moments. Sora2's AI will create your professional video with high-quality visuals and smooth transitions.

### Step 4: Download and Use

Once generated, download your video and use it immediately in your ${industry} marketing, training, or content strategy.

## Example Prompt for ${scene.use_case}

Here's an example prompt you can use with Sora2 to generate a **10-second or 15-second** video:

\`\`\`
[Example prompt based on the use case - will be generated based on scene description]
\`\`\`

**Note**: All videos generated by Sora2 are available in 10-second or 15-second durations. Choose the duration that best fits your content needs.

## Get Started Today

Start creating professional ${scene.use_case} videos for ${industry} today with Sora2 AI video generation platform. No technical skills required, no expensive equipment needed - just describe what you want, and AI will create it for you.`

  // 自动质量检查
  const qualityCheck = checkContentQuality({
    title,
    h1,
    description,
    content,
    seo_keywords: [scene.use_case, industry, `${industry} AI video`],
  })

  // 🔥 质量阈值检查：如果质量分数 < 40，跳过保存，避免保存低质量内容
  // 注意：正常生成的内容通常能拿到 60-100 分，40 分阈值只过滤严重低质量内容
  const QUALITY_THRESHOLD = 40
  if (qualityCheck.score < QUALITY_THRESHOLD) {
    const errorMessage = `质量分数过低 (${qualityCheck.score}/${QUALITY_THRESHOLD})，跳过保存。问题: ${qualityCheck.issues.join(', ')}`
    console.warn(`[${industry}] 场景词 ${scene.id} 质量过低，跳过保存:`, {
      score: qualityCheck.score,
      threshold: QUALITY_THRESHOLD,
      issues: qualityCheck.issues,
      warnings: qualityCheck.warnings,
      scenePreview: scene.use_case.substring(0, 100),
    })
    // 抛出特定错误，便于在 saveBatchScenes 中区分
    const qualityError = new Error(errorMessage) as Error & { isQualityTooLow?: boolean }
    qualityError.isQualityTooLow = true
    throw qualityError
  }

  // 根据质量检查结果设置状态
  const qualityStatus = qualityCheck.passed && qualityCheck.score >= 70 ? 'approved' : 'pending'
  const isPublished = qualityStatus === 'approved'

  // 直接使用 Supabase 保存（避免 HTTP 调用）
  // 🔥 添加超时控制，避免数据库操作卡住
  const DB_TIMEOUT = 10000 // 10秒超时
  
  try {
    // 🔥 使用 Promise.race 确保超时控制
    const insertPromise = supabase
      .from('use_cases')
      .insert({
        slug,
        title,
        h1,
        description,
        content,
        use_case_type: useCaseType,
        industry,
        is_published: isPublished,
        seo_keywords: [scene.use_case, industry, `${industry} AI video`],
        quality_status: qualityStatus,
        quality_score: qualityCheck.score,
        quality_issues: qualityCheck.issues,
      })
      .select()
    
    const timeoutPromise = new Promise<{ error: { message?: string; code?: string; details?: string; hint?: string } | null }>((_, reject) =>
      setTimeout(() => reject(new Error('数据库保存超时（10秒）')), DB_TIMEOUT)
    )
    
    const { error: insertError } = await Promise.race([insertPromise, timeoutPromise]) as { error: { message?: string; code?: string; details?: string; hint?: string } | null }

    if (insertError) {
      // 如果是重复 slug：视为重复内容，直接跳过（避免无限堆积重复记录）
      if (insertError.code === '23505') {
        const duplicateError = new Error(`Duplicate slug detected (likely duplicate use_case), skipped. slug=${slug}`) as Error & {
          isDuplicate?: boolean
        }
        duplicateError.isDuplicate = true
        throw duplicateError
      } else {
        console.error(`[${industry}] 保存失败:`, {
          error: insertError.message,
          code: insertError.code,
          details: insertError.details,
          hint: insertError.hint,
          slug,
          useCaseType,
        })
        throw new Error(`保存失败: ${insertError.message} (code: ${insertError.code})`)
      }
    }
  } catch (error) {
    // 记录更详细的错误信息
    const errorMessage = error instanceof Error ? error.message : String(error)
    console.error(`[${industry}] 保存场景词异常:`, {
      error: errorMessage,
      sceneId: scene.id,
      sceneLength: scene.use_case.length,
      slug,
      useCaseType,
    })
    throw error
  }
}

